packages:
  - apps/*
  - packages/*
  - services/*
  - infra

tasks:
  build:
    dependsOn: ['^build']
  typecheck:
    dependsOn: ['^build']
  test:
    dependsOn: ['^build']
  check:
    dependsOn: [lint, typecheck, test, build]
  generate:
    dependsOn: ['^generate']
