# generated by datamodel-codegen:
#   filename:  health_response.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field


class HealthResponse(BaseModel):
    """
    Liveness check response.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    status: Annotated[Literal["ok"], Field(description='Always "ok" when the service is up.')]
